# Generated by Django 3.2.5 on 2021-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='is_deleted',
        ),
    ]
