# Generated by Django 3.2.5 on 2021-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_remove_shopuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
