# Generated by Django 3.2.5 on 2021-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_shopuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='пользователь активен'),
        ),
    ]
