# Generated by Django 3.2.5 on 2021-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('AP', 'ожидает оплаты'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('RDY', 'отправлен'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
